title: My Amazing Site
author: My Name
email: my-email@domain.com
description: >
  This is my amazing site!
copyright: My Name

# EnchantedCode Theme Configs

# enable excerpts on post previews
#show_excerpts: false

# enable the site breadcrumb (default is false)
enable_breadcrumb: true

# date format for human readable post meta
#date_format: "%b %-d, %Y"

# link specific pages to header navbar
#header_pages:
# - about.md

# use theme with jekyll-remote-theme
#remote_theme: enchant97/enchantedcode-theme

plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
 # uncomment this if loading the theme with remote_theme
 #- jekyll-remote-theme

# Change the homepage heading
#welcome_msg: "Welcome To The \"Amazing Site\""

# enable pagination
#paginate: 8
#paginate_path: "/page:num/"
